"""Single source of truth for the restrained DotLingo visual system."""

TOKENS = {
    "bg": "#11191d",
    "surface": "#172126",
    "surface_raised": "#1d2a2f",
    "surface_hover": "#26373b",
    "border": "#34464a",
    "border_focus": "#72d6c2",
    "text": "#e6eee9",
    "muted": "#9aaba8",
    "accent": "#72d6c2",
    "accent_dim": "#244a47",
    "warning": "#e8bb75",
    "error": "#e28579",
    "success": "#82c99d",
    "highlight": "#374b4b",
    "font": "Segoe UI",
    "mono": "Cascadia Mono",
    "font_small": 9,
    "font_body": 10,
    "font_title": 16,
    "font_heading": 12,
    "spacing_xs": 4,
    "spacing_sm": 8,
    "spacing_md": 14,
    "spacing_lg": 22,
    "radius": 10,
    "reduced_motion": True,
}
