"""Single source of truth for the DotLingo visual system."""

TOKENS = {
    "bg": "#f4f2ec",
    "surface": "#fbfaf6",
    "surface_raised": "#ffffff",
    "surface_hover": "#edf1f1",
    "border": "#d9dcd8",
    "border_soft": "#e8e9e4",
    "border_focus": "#547a8b",
    "text": "#202a30",
    "muted": "#657178",
    "accent": "#315f70",
    "accent_dim": "#274e5d",
    "warning": "#a85f3d",
    "error": "#b34f48",
    "success": "#4f765e",
    "highlight": "#dce9eb",
    "font": "Segoe UI",
    "mono": "Cascadia Mono",
    "font_small": 10,
    "font_body": 12,
    "font_title": 28,
    "font_heading": 17,
    "spacing_xs": 5,
    "spacing_sm": 9,
    "spacing_md": 14,
    "spacing_lg": 22,
    "reduced_motion": False,
}
